server:
  port: 8084

spring:
  application:
    name: fraud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bankhub
    username: bankhub
    password: bankhub123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Fraud Detection Configuration
fraud:
  detection:
    max-transaction-amount: 10000.00
    max-daily-transactions: 10
    suspicious-hour-start: 0
    suspicious-hour-end: 6
    risk-score-threshold: 75.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics